name: Build wheels

on: [push, pull_request] 
    
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        architecture: [x64, x86, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python for Windows (Only on Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: ${{ matrix.architecture }}

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.architecture }}
          CIBW_ARCHS_MACOS: ${{ matrix.architecture }}
          CIBW_ARCHS_WINDOWS: ${{ matrix.architecture }}
          CIBW_SKIP: "cp36-* cp37-*"
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: List wheels
        run: |
          ls wheelhouse

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-wheels
          path: wheelhouse/*.whl