name: Build wheels

on: [push, pull_request] 
    
jobs:
  build_wheels:
    name: ${{ matrix.os }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        architecture: [x86_64]
        include:
          - os: ubuntu-latest
            architecture: aarch64
          - os: macos-latest
            architecture: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.architecture }}
          CIBW_ARCHS_MACOS: ${{ matrix.architecture }}
          CIBW_SKIP: "cp36-* cp37-*"
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: List wheels
        run: |
          ls wheelhouse

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-wheels
          path: wheelhouse/*.whl
          
  build_wheels_windows:
    name: ${{ matrix.os }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        architecture: [x86, AMD64, ARM64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python for Windows (Only on Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_ARCHS_WINDOWS: ${{ matrix.architecture }}
          CIBW_SKIP: "cp36-* cp37-*"
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: List wheels
        run: |
          ls wheelhouse

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-wheels
          path: wheelhouse/*.whl